services:
  db:
    image: postgres:15-alpine
    container_name: treinfomap-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: treinfomap-web
    depends_on:
      - db
    ports:
      - "2412:5000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=trein_secret_key_v10
    volumes:
      - .:/app
      - /app/static/img
      - /app/gtfs_data
    restart: always

volumes:
  postgres_data:
